name: CI

on:
  push:
    branches: [ master, task4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        cd task4/TechProgCITemplate
        git clone https://github.com/google/googletest.git
        mv googletests/ 3rdparty
        cd ..
        mkdir build
        cmake ..
        make
        cd ..
