name: CI

on:
  push:
    branches: [ master, task4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd task4/TechProgCITemplate
        mkdir 3rdparty
        git clone https://github.com/google/googletest.git 3rdparty
        mkdir build
        cd build
        cmake ..
        make
        cd ..

    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: ./bin/CTestExe
        report-path: ./report.xml
        working-directory: .
    - name: UploadArtifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./lib
