name: CI

on:
  push:
    branches: [ master, task4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        ls -al
        cd task4/TechProgCITemplate
        ls -al
        git clone https://github.com/google/googletest.git
        mv googletest/ 3rdparty
        ls -al
        mkdir build
        cd build
        cmake ..
        make
